eb setenv AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION POSTGRES_USERNAME=$POSTGRES_USERNAME POSTGRES_PASSWORD=$POSTGRES_PASSWORD PORT_DB=$PORT_DB PORT=$PORT POSTGRES_HOST=$POSTGRES_HOST  AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION  AWS_BUCKET=$AWS_BUCKET URL=$URL JWT_SECRET=$JWT_SECRET --profile default


